VAL-604 Added API documentation for provider_lookup flag
mailgun/documentation pull request #510
Opened 2020-09-24 19:14 UTC by zach-godd

https://mailgun.atlassian.net/browse/VAL-604

2020-09-24 20:33 UTC, aerwin3 requested changes

2020-09-24 20:33 UTC, aerwin3 commented on source/api-email-validation.rst
> +The provider_lookup query parameter provides users with the control to allow or prevent Mailgun from reaching out to the mailbox provider or rely on Mailgun’s internal analysis alone.
Can we remove the "or rely on Mailgun's internal analysis alone"?

2020-09-24 20:42 UTC, jamiramontez commented on source/api-email-validation.rst
> +The provider_lookup query parameter provides users with the control to allow or prevent Mailgun from reaching out to the mailbox provider or rely on Mailgun’s internal analysis alone.
that's fine

2020-09-25 14:16 UTC, zach-godd commented on source/api-email-validation.rst
> +The provider_lookup query parameter provides users with the control to allow or prevent Mailgun from reaching out to the mailbox provider or rely on Mailgun’s internal analysis alone.
Just made the change. Also, I added a yellow warning tag instead of italics around the "For advanced users only" line.

2020-09-25 15:53 UTC, zach-godd commented on source/api-email-validation.rst
> +The provider_lookup query parameter provides users with the control to allow or prevent Mailgun from reaching out to the mailbox provider or rely on Mailgun’s internal analysis alone.
@aerwin3 please review

2020-09-25 15:56 UTC, aerwin3 approved these changes

2020-09-25 15:57 UTC, merged