Update Inbox Placement API repsonse
mailgun/documentation pull request #545
Opened 2021-09-02 22:36 UTC by marco258

2021-09-02 23:14 UTC, roaet commented on source/samples/fields-ibp-seed-lists.rst
> +results                  array        An array of tests performed on the seed list.
`An array of tests performed` is a little weird. It's more like test results using from this seed list. or results from the seed list's tests.

2021-09-02 23:14 UTC, roaet commented on source/samples/get-results.rst
> +      https://api.mailgun.net/v4/inbox/results
whew good catch. 👍🏼

2021-09-02 23:15 UTC, roaet requested changes
Just the little changes would be good.

2021-09-03 15:21 UTC, roaet commented on source/samples/fields-ibp-seed-lists.rst
> +results                  array        An array of results from the seed list's test.
nit: `test` -> `tests`. not sure if that is correct grammar though

2021-09-03 15:21 UTC, roaet approved these changes
⛄

2021-09-03 15:24 UTC, marco258 commented on source/samples/fields-ibp-seed-lists.rst
> +results                  array        An array of results from the seed list's test.
I believe `tests` is correct, updated. :)

2021-09-03 15:25 UTC, merged