Flex plan updates
mailgun/documentation pull request #574
Opened 2022-02-01 22:38 UTC by jeffturpin1987

Flex Plan Updates

2022-02-01 22:56 UTC, jeffturpin1987 commented
As a note: only one .rst file is changed (and it's the changes for the release today) though for some reason the comments from my previous PR are listed.

2022-02-03 18:40 UTC, haskellj requested changes

2022-02-03 18:40 UTC, haskellj commented on source/faqs.rst
> +If you opt to enter your credit card during sign-up, you'll enter a three-month trial in which your card will not be charged unless you exceed the 5,000 messages per month allotment. After your trial
Not quite right. Those currently on the Flex Trial plan will automatically be moved to the normal Flex plan at the end of their 3-month trial.

The new trial plan is called Foundation Trial and THAT one will automatically move customers to the $35/mo Foundation 50k plan at the end of their 3 month trial. So you may want to add the new plan as its own paragraph or replace the Flex Trial paragraph completely.

2022-02-09 19:47 UTC, jeffturpin1987 commented on source/faqs.rst
> +If you opt to enter your credit card during sign-up, you'll enter a three-month trial in which your card will not be charged unless you exceed the 5,000 messages per month allotment. After your trial
I've updated this and I've had a member of the marketing team review the "as-is" and the "to-be" and she said it looks good!

2022-02-15 21:00 UTC, haskellj approved these changes

2022-02-15 21:11 UTC, merged