Add Email Preview API documentation
mailgun/documentation pull request #582
Opened 2022-04-07 19:49 UTC by jeffreyjurgajtis

This PR adds documentation for Email Previews including the following endpoints:

- POST /v1/preview/tests
- GET /v1/preview/tests
- GET /v1/preview/tests/{TEST_ID}
- GET /v1/preview/tests/{TEST_ID}/results
- GET /v1/preview/tests/{TEST_ID}/content
- DELETE /v1/preview/tests/{TEST_ID}
- PUT /v1/preview/tests/{TEST_ID}/results/reprocess
- GET /v1/preview/tests/clients

2022-04-07 20:05 UTC, mkbond requested changes
2 comments but the rest LGTM!

2022-04-07 20:05 UTC, mkbond commented on source/api-email-preview.rst
> +This call will automatically requeue screenshots if they stay in processing for more than threeminutes.
```suggestion
This call will automatically requeue screenshots if they stay in processing for more than three minutes.
```

2022-04-07 20:19 UTC, roaet approved these changes
⛄

2022-04-07 20:19 UTC, roaet commented
Great docs

2022-04-07 20:21 UTC, jeffreyjurgajtis commented on source/api-email-preview.rst
> +Create Test
good call! added in https://github.com/mailgun/documentation/pull/582/commits/3bf51ddbc12be414d136f6cf9e84793a0eb20279

2022-04-07 20:22 UTC, jeffreyjurgajtis commented on source/api-email-preview.rst
> +This call will automatically requeue screenshots if they stay in processing for more than threeminutes.
good catch! fixed in https://github.com/mailgun/documentation/pull/582/commits/3bf51ddbc12be414d136f6cf9e84793a0eb20279

2022-04-07 20:24 UTC, mkbond approved these changes

2022-04-07 20:53 UTC, merged

2022-04-08 17:58 UTC, Jvb182 commented
Baller